### ISSUE TITLE
Multiple radio groups issue

### ISSUE THREAD

**Issue by Radmation** [rubentd/radios-to-slider#11]
Hi there,

I have multiple radio groups in my form and when I try to call radiosToSlider() on more than one div - I have issues. 

Here is my form..

                         `<form class="form-horizontal" enctype="multipart/form-data">
            <div class="form-group">
                <label for="firstName" class="control-label col-sm-2">Your Name</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" name="firstName" id="firstName">
                </div>
            </div>

            <div class="form-group">
                <label for="companyName" class="control-label col-sm-2">Company Name</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" name="companyName" id="companyName">
                </div>
            </div>

            
            <div class="form-group">
                <label for="radios1" class="control-label col-sm-2">How Many Stores Do You Operate?</label>
                <div class="col-sm-10">

                    <div id="radios1">

                        <input id="one" name="storesOperated" value="one" type="radio">
                        <label for="one">1</label>

                        <input id="twofive" name="storesOperated" value="twofive" type="radio">
                        <label for="twofive">2-5</label>

                        <input id="fiveten" name="storesOperated" value="fiveten" type="radio">
                        <label for="fiveten">5-10</label>

                        <input id="tenplus" name="storesOperated" value="tenplus" type="radio">
                        <label for="tenplus">10+</label>

                    </div>
                </div>
            </div>

            
            
            
            
            
            

            <div class="form-group">
                <label for="email" class="control-label col-sm-2">Email</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" name="email" id="email">
                </div>
            </div>

            <div class="form-group">
                <label for="phone" class="control-label col-sm-2">Phone</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" name="phone" id="phone">
                </div>
            </div>

            <div class="form-group">
                <label for="reachTime" class="control-label col-sm-2">Best Time to Reach You</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" name="reachTime" id="reachTime">
                    
                </div>
            </div>

            
            <div class="form-group">
                <label for="radios2" class="control-label col-sm-2">What Size Cups Are of Interest?</label>
                <div class="col-sm-10">

                    <div id="radios2">
                        <input id="2oz" name="cupsInterest" value="2oz" type="radio">
                        <label for="2oz">2oz</label>

                        <input id="4oz" name="cupsInterest" value="4oz" type="radio">
                        <label for="4oz">4oz</label>

                        <input id="5oz" name="cupsInterest" value="5oz" type="radio">
                        <label for="5oz">5oz</label>

                        <input id="6oz" name="cupsInterest" value="6oz" type="radio">
                        <label for="6oz">6oz</label>

                        <input id="8oz" name="cupsInterest" value="8oz" type="radio">
                        <label for="8oz">8oz</label>

                        <input id="9oz" name="cupsInterest" value="9oz" type="radio">
                        <label for="9oz">9oz</label>

                        <input id="10oz" name="cupsInterest" value="10oz" type="radio">
                        <label for="10oz">10oz</label>

                        <input id="12oz" name="cupsInterest" value="12oz" type="radio">
                        <label for="12oz">12oz</label>

                        <input id="16oz" name="cupsInterest" value="16oz" type="radio">
                        <label for="16oz">16oz</label>

                        <input id="20oz" name="cupsInterest" value="20oz" type="radio">
                        <label for="20oz">20oz</label>

                        <input id="24oz" name="cupsInterest" value="24oz" type="radio">
                        <label for="24oz">24oz</label>

                        <input id="32oz" name="cupsInterest" value="32oz" type="radio">
                        <label for="32oz">32oz</label>

                    </div>
                </div>
            </div>

            <div class="form-group">
                <label for="cupType" class="control-label col-sm-2">What Type of Cups Are of Interest?</label>
                <div class="col-sm-10">
                    <select name="cupType" id="cupType" class="form-control">
                        <option value="paperHot">Paper Hot</option>
                        <option value="paperCold">Paper Cold</option>
                        <option value="containerHot">Container - Hot</option>
                        <option value="containerCold">Container - Cold</option>
                        <option value="clearPlasticPET">Clear Plastic PET</option>
                        <option value="clearPlasticPP">Clear Plastic PP</option>
                        <option value="lids">Lids</option>
                        <option value="iceCreamPaperLid">Ice Cream-Paper Lid</option>
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label for="annualUsage" class="control-label col-sm-2">Annual Usage?</label>
                <div class="col-sm-10">
                    <select name="annualUsage" id="annualUsage" class="form-control">
                        <option value="1000">1,000</option>
                        <option value="5000">5,000</option>
                        <option value="10000">10,000</option>
                        <option value="30000">30,000</option>
                        <option value="100000">100,000+</option>
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label for="expectedDelivery" class="control-label col-sm-2">Expected Delivery Date</label>
                <div class="col-sm-10">
                    <select name="expectedDelivery" id="expectedDelivery" class="form-control">
                        <option value="rush">Rush</option>
                        <option value="10days">10 days</option>
                        <option value="30days">30 days</option>
                        <option value="65days">65 days</option>
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label for="uploadLogo" class="control-label col-sm-2">Upload Logo</label>
                <div class="col-sm-10">
                    <input type="file" class="form-control" name="uploadLogo" id="uploadLogo">
                    
                </div>
            </div>

        </form>`
Here is me calling two groups..

$(document).ready( function () {

    $('#radios1').radiosToSlider({
    });

    $('#radios2').radiosToSlider({
    });

});

Thanks!

**Comment by lloydie-t** [comment]
Hi Radmation, I had the same problem only yesterday. In the end I did a rough fix myself as I neded it urgently. Please find the following chnages I made to the setSlider function.
```javascript
//set width of slider bar and current level
		setSlider: function(){
			var radio=1;
			var slider=this;
                        
			this.bearer.find('input[type=radio]').each( function(){
				var radioId=$(this).attr('id');
				if($(this).prop('checked')){
                                        var option = $(this).closest('div[id]');
                                        var noOfInputs=0;
                                        $(option).find('input[type="radio"]').each(function(){
                                            if ($.trim($(this).val()).length) {
                                                noOfInputs+=1;
                                            }
                                        });
                                        
                                        KNOB_MARGIN = (option.width()-KNOB_WIDTH) / (noOfInputs-1) - KNOB_WIDTH;
					slider.bearer.find('.slider-bar').css('display', 'block');
					slider.bearer.find('.slider-bar').width( (radio*KNOB_WIDTH) + (radio-1)*KNOB_MARGIN + 'px');
					slider.currentLevel=radio;
				}
				if(slider.options.animation){
					slider.bearer.find('.slider-bar').addClass('transition-enabled');
				}
				radio++;
			});
```
Please forgive the poor JS coding as it is not my fortay, but it works for me!

**Comment by wodka** [comment]
jsfiddle of this error: https://jsfiddle.net/nL9cr5xj/
