### ISSUE TITLE
Change Event detection

### ISSUE THREAD

**Issue by Monil200** [rubentd/radios-to-slider#2]
this radio to slider is not being able to detect click/change events..is it?

**Comment by ghopgood** [comment]
Add .trigger("change") to the js file.

addInteraction: function(){
			var slider=this;

			this.bearer.find('.slider-level').click( function(){
				var radioId = $(this).attr('data-radio');
				slider.bearer.find('#' + radioId).prop('checked', true)**.trigger("change");**
				slider.setSlider();

			});

			this.bearer.find('input[type=radio]').change(function(){
				slider.setSlider();
			});

		}

Then the change function on your calling page must come before the initialization of the radios

**Comment by Monil200** [comment]
thanks all. That helped.
