### ISSUE TITLE
Resizing slider and knob

### ISSUE THREAD

**Issue by nocean** [rubentd/radios-to-slider#4]
Thanks for this great script. I'm having trouble figuring out the correlation between the KNOB_WIDTH, KNOB_MARGIN and the various CSS rules that style things. I'd like to increase the size of the slider, and while the new auto-width feature works smashingly, adjusting the height and knob size is a bit tedious. Can you offer any insight into how to adjust these various variables to accomplish additional customization?

**Comment by Yana1** [comment]
I also had such problem, couldn't make radios div to fit 100% to its container and solved this issue by replacing  jquery.radios-to-slider.min.js with jquery.radios-to-slider.js.
Some options are absent in  jquery.radios-to-slider.min.js. So If you use jquery.radios-to-slider.min.js, just replace it with jquery.radios-to-slider.js, maybe this will help.

**Comment by rubentd** [comment]
Thanks, I'll update the minified version
